/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#ifndef __PLUGINEDITOR_H_8F738F8__
#define __PLUGINEDITOR_H_8F738F8__

#include "../JuceLibraryCode/JuceHeader.h"
#include "PluginProcessor.h"


//==============================================================================
/**
*/
class PulseDelayAudioProcessorEditor  : public AudioProcessorEditor
{
public:
    PulseDelayAudioProcessorEditor (PulseDelayAudioProcessor* ownerFilter);
    ~PulseDelayAudioProcessorEditor();

    //==============================================================================
    // This is just a standard Juce paint method...
    void paint (Graphics& g);
};


#endif  // __PLUGINEDITOR_H_8F738F8__
